### ISSUE TITLE
please share the data

### ISSUE THREAD

**Issue by zhuhongweiyi** [qiexing/caffe-regression#3]
Thanks for sharing the code!
could you share me the kaggle data?because i can not download it from from https://www.kaggle.com/c/facial-keypoints-detection/data. 
thank you very much!

**Comment by qiexing** [comment]
Hi, this link can work. If you are new to kaggle, you need to register then download the data.

**Comment by zhuhongweiyi** [comment]
because i need Proxy ,i can not  register .
can you share the data?
thank you very much!
